//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlexaSkill.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompetitionWinner
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Tweet { get; set; }
        public string ProfileImageUrl { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    }
}
